### ISSUE TITLE
Imagens quebradas

### ISSUE THREAD

**Issue by rubensantoniorosa2704** [Thiagox27/projeto.figma#1]
**As imagens do projeto não foram adicionadas ao repositório**. Favor fazer um commit com os arquivos das imagens para que outros possam colaborar com o projeto ;))
![Captura de tela de 2023-04-18 21-18-34](https://user-images.githubusercontent.com/86082354/232932782-76fbcf98-bba2-4ddd-9c2c-43ae9c4ccd84.png)

**Comment by Thiagox27** [comment]
ok ja foi resolvido

**Comment by Thiagox27** [comment]
resolvido
